/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPedidos;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario1
 */
public class FrmHacerPedido extends javax.swing.JFrame {

    /**
     * Creates new form FrmHacerPedido
     */
    public FrmHacerPedido() {
        initComponents();
        transparenciaBoton();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Hacer pedido");
        setSize(640, 512);
        ImageIcon fondo = new ImageIcon("C:/Users/Asrock/Documents/Semestre may-sep 21/POO/PROYECTO/Version 10 de sep/GUIProyectoMongoApp/src/guiproyectomongoapp/Imagenes/prueba.png");
        Icon icono= new ImageIcon(fondo.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
        jLabel6.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreClientePedido = new javax.swing.JTextField();
        txtDescripcionPedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDireccionPedido = new javax.swing.JTextField();
        btnEnviarPedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnPagarDebito = new javax.swing.JButton();
        btnPagarTarjeta = new javax.swing.JButton();
        txtSeleccionado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese su nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese la descripcion del pedido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtNombreClientePedido.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.add(txtNombreClientePedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 530, 33));

        txtDescripcionPedido.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.add(txtDescripcionPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 530, 36));

        jLabel3.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel3.setText("Crear Pedido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 187, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel4.setText("Ingrese su direccion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtDireccionPedido.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.add(txtDireccionPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 530, 37));

        btnEnviarPedido.setBackground(new java.awt.Color(51, 255, 51));
        btnEnviarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/enviar.png"))); // NOI18N
        btnEnviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("ENVIAR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 60, 20));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/BotonRegrese1.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel7.setText("Seleccione el metodo de pago:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 340, 40));

        btnPagarDebito.setBackground(new java.awt.Color(51, 255, 51));
        btnPagarDebito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/debito.png"))); // NOI18N
        btnPagarDebito.setText("Efectivo");
        jPanel1.add(btnPagarDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, -1));

        btnPagarTarjeta.setBackground(new java.awt.Color(51, 255, 51));
        btnPagarTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/tarjeta.png"))); // NOI18N
        btnPagarTarjeta.setText("Tarjeta de credito o debito");
        btnPagarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagarTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 230, -1));

        txtSeleccionado.setBackground(new java.awt.Color(102, 255, 102));
        txtSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeleccionadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 160, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/prueba.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void transparenciaBoton(){
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false);
//        btnPagarDebito.setOpaque(false);
//        btnPagarDebito.setContentAreaFilled(false);
//        btnPagarDebito.setBorderPainted(false);
//        btnPagarTarjeta.setOpaque(false);
//        btnPagarTarjeta.setContentAreaFilled(false);
//        btnPagarTarjeta.setBorderPainted(false);
        
        
    }
    private void btnEnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPedidoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Su pedido se ha enviado correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnEnviarPedidoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPagarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarTarjetaActionPerformed

    private void txtSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeleccionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeleccionadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        FrmHacerPedido v = new FrmHacerPedido();
//        FrmListaPedidos x = new FrmListaPedidos();
//        ControladorPedidos c = new ControladorPedidos(v,x);
//        v.setVisible(true);
//        v.setLocationRelativeTo(v);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHacerPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEnviarPedido;
    public javax.swing.JButton btnPagarDebito;
    public javax.swing.JButton btnPagarTarjeta;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtDescripcionPedido;
    public javax.swing.JTextField txtDireccionPedido;
    public javax.swing.JTextField txtNombreClientePedido;
    public javax.swing.JTextField txtSeleccionado;
    // End of variables declaration//GEN-END:variables
}
