/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorRepartidores;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario1
 */
public class FrmAgregarRepartidores extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgregarRepartidores
     */
    public FrmAgregarRepartidores() {
        initComponents();
        transparenciaBoton();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Agregar Repartidores");
        setSize(746, 373);
        ImageIcon fondo = new ImageIcon("C:/Users/Asrock/Documents/Semestre may-sep 21/POO/PROYECTO/Version 10 de sep/GUIProyectoMongoApp/src/guiproyectomongoapp/Imagenes/prueba.png");
        Icon icono= new ImageIcon(fondo.getImage().getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_DEFAULT));
        jLabel8.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreRepartidor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoRepartidor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedulaRepartidor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumeroPlacaRepartidor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreoRepartidor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pwContraseñaRepartidor = new javax.swing.JPasswordField();
        btnGuardarRepartidores = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel1.setText("Agregar repartidores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, -1, -1));

        txtNombreRepartidor.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtNombreRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 64, 199, 31));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 62, -1, 28));

        txtApellidoRepartidor.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtApellidoRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 64, 199, 31));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel4.setText("Cedula:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, 33));

        txtCedulaRepartidor.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtCedulaRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 113, 199, 33));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel5.setText("Nº Placa:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 113, -1, 33));

        txtNumeroPlacaRepartidor.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtNumeroPlacaRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 113, 199, 33));

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel6.setText("Correo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, -1, 34));

        txtCorreoRepartidor.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtCorreoRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 167, 338, 34));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 219, -1, 35));

        pwContraseñaRepartidor.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(pwContraseñaRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 222, 338, 35));

        btnGuardarRepartidores.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardarRepartidores.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        btnGuardarRepartidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/save.png"))); // NOI18N
        btnGuardarRepartidores.setText("GUARDAR");
        btnGuardarRepartidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRepartidoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarRepartidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 293, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/BotonRegrese1.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 293, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/prueba.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void transparenciaBoton(){
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false);
        
    }
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarRepartidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRepartidoresActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Cuenta repartidor se ha guardado correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnGuardarRepartidoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarRepartidores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardarRepartidores;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField pwContraseñaRepartidor;
    public javax.swing.JTextField txtApellidoRepartidor;
    public javax.swing.JTextField txtCedulaRepartidor;
    public javax.swing.JTextField txtCorreoRepartidor;
    public javax.swing.JTextField txtNombreRepartidor;
    public javax.swing.JTextField txtNumeroPlacaRepartidor;
    // End of variables declaration//GEN-END:variables
}
