/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipaisesapp;

import java.util.ArrayList;

/**
 *
 * @author AsrockLeo
 */
public class frmPaises extends javax.swing.JFrame {

    /**
     * Creates new form frmPaises
     */
    public frmPaises() {
        initComponents();
        llenarComboArreglo();
        llenarComboObjetos();
    }
    private void llenarComboArreglo(){
        String[] paises= {"Chile","Mexico","Bolivia"};
        for(String pais:paises){
            cmbPaisB.addItem(pais);
        }
    }
    private void llenarComboObjetos(){
        ArrayList<Pais> listaP = new ArrayList<Pais>();
        Pais p1= new Pais(1,"España");
        Pais p2= new Pais(2,"Italia");
        Pais p3= new Pais(3,"Portugal");
        listaP.add(p1);
        listaP.add(p2);
        listaP.add(p3);
        for(Pais aux : listaP){
            cmbPaisC.addItem(aux);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbPaisA = new javax.swing.JComboBox<>();
        btnEscogerA = new javax.swing.JButton();
        cmbPaisB = new javax.swing.JComboBox<>();
        cmbPaisC = new javax.swing.JComboBox<>();
        btnEscogerB = new javax.swing.JButton();
        btnEscogerC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSeleccionado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 11, 88));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cmbPaisA.setBackground(new java.awt.Color(51, 51, 51));
        cmbPaisA.setForeground(new java.awt.Color(0, 153, 255));
        cmbPaisA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ecuador", "Peru", "Colombia" }));
        cmbPaisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaisAActionPerformed(evt);
            }
        });

        btnEscogerA.setBackground(new java.awt.Color(59, 107, 197));
        btnEscogerA.setForeground(new java.awt.Color(0, 0, 0));
        btnEscogerA.setText("Escoger A");
        btnEscogerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerAActionPerformed(evt);
            }
        });

        cmbPaisB.setBackground(new java.awt.Color(51, 51, 51));
        cmbPaisB.setForeground(new java.awt.Color(0, 153, 255));

        cmbPaisC.setBackground(new java.awt.Color(51, 51, 51));
        cmbPaisC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaisCActionPerformed(evt);
            }
        });

        btnEscogerB.setBackground(new java.awt.Color(60, 93, 186));
        btnEscogerB.setForeground(new java.awt.Color(0, 0, 0));
        btnEscogerB.setText("Escoger B");
        btnEscogerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerBActionPerformed(evt);
            }
        });

        btnEscogerC.setBackground(new java.awt.Color(60, 118, 197));
        btnEscogerC.setForeground(new java.awt.Color(0, 0, 0));
        btnEscogerC.setText("Escoger C");
        btnEscogerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerCActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ITEM ESCOGIDO");

        txtSeleccionado.setBackground(new java.awt.Color(69, 98, 163));
        txtSeleccionado.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPaisB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPaisA, 0, 86, Short.MAX_VALUE)
                            .addComponent(cmbPaisC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEscogerA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEscogerB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEscogerC, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(txtSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPaisA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscogerA))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPaisB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscogerB))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPaisC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscogerC))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscogerAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerAActionPerformed
        // TODO add your handling code here:
        String item=cmbPaisA.getSelectedItem().toString();
        txtSeleccionado.setText(item);
    }//GEN-LAST:event_btnEscogerAActionPerformed

    private void btnEscogerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerBActionPerformed
        // TODO add your handling code here:
        String item=cmbPaisB.getSelectedItem().toString();
        txtSeleccionado.setText(item);
    }//GEN-LAST:event_btnEscogerBActionPerformed

    private void btnEscogerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerCActionPerformed
        // TODO add your handling code here:
        Pais item =(Pais)cmbPaisC.getSelectedItem();
        txtSeleccionado.setText(item.getNombre());
    }//GEN-LAST:event_btnEscogerCActionPerformed

    private void cmbPaisCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPaisCActionPerformed

    private void cmbPaisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPaisAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPaises().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscogerA;
    private javax.swing.JButton btnEscogerB;
    private javax.swing.JButton btnEscogerC;
    private javax.swing.JComboBox<String> cmbPaisA;
    private javax.swing.JComboBox<String> cmbPaisB;
    private javax.swing.JComboBox<Object> cmbPaisC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSeleccionado;
    // End of variables declaration//GEN-END:variables
}
