/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorClientes;
import Controlador.GestorUsuarios;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario1
 */
public class FrmRegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistroCliente
     */
    private static Scanner sc;
    private static int intentos;
    private static String user,password;
    public FrmRegistroCliente() {
        initComponents();
        transparenciaBoton();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registro del Cliente");
        setSize(630, 480);
        ImageIcon fondo = new ImageIcon("C:/Users/Asrock/Documents/Semestre may-sep 21/POO/PROYECTO/GUIProyectoMongoApp/src/guiproyectomongoapp/Imagenes/prueba.png");
        Icon icono= new ImageIcon(fondo.getImage().getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_DEFAULT));
        jLabel9.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRegistroNombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRegistroCedulaCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRegistroCelularCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pwContraseñaRegistroCliente = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtCorreoRegistroCliente = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnGuardarCliente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionRegistroCliente = new javax.swing.JTextField();
        txtRegistroApellidoCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Formulario de Registro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 229, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 84, 38));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 45, 72, 40));

        txtRegistroNombreCliente.setBackground(new java.awt.Color(153, 255, 153));
        txtRegistroNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroNombreClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtRegistroNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 184, 38));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nº de Cedula:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, 36));

        txtRegistroCedulaCliente.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtRegistroCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 184, 36));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Celular:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 105, 72, 38));

        txtRegistroCelularCliente.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtRegistroCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 107, 200, 39));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 36));

        pwContraseñaRegistroCliente.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(pwContraseñaRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 370, 36));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Correo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 74, 39));

        txtCorreoRegistroCliente.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtCorreoRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 371, 39));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/BotonRegrese1.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 50, 50));

        btnGuardarCliente.setBackground(new java.awt.Color(102, 255, 102));
        btnGuardarCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnGuardarCliente.setText("GUARDAR");
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Direccion:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtDireccionRegistroCliente.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtDireccionRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 370, 40));

        txtRegistroApellidoCliente.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtRegistroApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 200, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproyectomongoapp/Imagenes/prueba.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void transparenciaBoton(){
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false);
        
    }
    private void txtRegistroNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroNombreClienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmLoginGeneral ventanaLoginGeneral = new FrmLoginGeneral();
        ventanaLoginGeneral.show();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        // TODO add your handling code here:
        String nombreArchivo= "Clientes";
        String carpeta= System.getProperty("user.dir");//toma la direccion en la que se va a alojar el archivo
        String direccionCompleta= carpeta +"/"+nombreArchivo+".txt";
        FileWriter ubicacion=null;
        
        
        try{

            ubicacion= new FileWriter(direccionCompleta);

        }catch(IOException ex){
            Logger.getLogger(GestorUsuarios.class.getName()).log(Level.SEVERE,null,ex);
        }
        try{

            BufferedWriter escritor= new BufferedWriter(ubicacion);


            escritor.write(txtCorreoRegistroCliente.getText()+"\n");
            escritor.write(pwContraseñaRegistroCliente.getText()+"\n");
            escritor.write(txtRegistroNombreCliente.getText()+"\n");
            escritor.write(txtRegistroApellidoCliente.getText()+"\n");
            escritor.write(txtRegistroCedulaCliente.getText()+"\n");
            escritor.write(txtRegistroCelularCliente.getText()+"\n");
            escritor.write(txtDireccionRegistroCliente.getText()+"\n");
            
            
            
            


            escritor.close();
        }catch(Exception ex ){

        }
        FileReader fr= null;
        try {
            int nLineas=0;
            int i=0;
            String [] usuarios=null;
            String linea;

            sc= new Scanner(new File(direccionCompleta));
            File f= new File(direccionCompleta);

            fr= new FileReader(f);
            BufferedReader br= new BufferedReader(fr);
            try {
                while((linea=br.readLine())!=null){
                    nLineas++;
                    
                }
                
                } catch (IOException ex) {
                Logger.getLogger(FrmLoginGeneral.class.getName()).log(Level.SEVERE, null, ex);
            }
            usuarios=new String[nLineas]; //tamaño del array
            while(sc.hasNextLine()){
                usuarios[i++]=sc.nextLine(); //almacenando cada linea en una posicion del arreglo
            }
            //intentos++;
            user = txtCorreoRegistroCliente.getText();
            password= pwContraseñaRegistroCliente.getText();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmLoginGeneral.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Su cuenta cliente se ha guardado correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        FrmLoginGeneral ventanaLoginGeneral = new FrmLoginGeneral();
        ventanaLoginGeneral.show();
        this.dispose();
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FrmRegistroCliente v = new FrmRegistroCliente();
        ControladorClientes c = new ControladorClientes(v);
        v.setVisible(true);
        v.setLocationRelativeTo(v);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardarCliente;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField pwContraseñaRegistroCliente;
    public javax.swing.JTextField txtCorreoRegistroCliente;
    public javax.swing.JTextField txtDireccionRegistroCliente;
    public javax.swing.JTextField txtRegistroApellidoCliente;
    public javax.swing.JTextField txtRegistroCedulaCliente;
    public javax.swing.JTextField txtRegistroCelularCliente;
    public javax.swing.JTextField txtRegistroNombreCliente;
    // End of variables declaration//GEN-END:variables
}
